myblog/config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :posts do
      resources :comments
    end

    root 'posts#index'
end

myblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myblog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post,class_name: :Post
  validates :body, presence: true
end

myblog/app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, class_name: :Comment, foreign_key: :post_id, dependent: :destroy
    # @post.comment
    validates :title, presence: true, length: {minimum: 3 }
    validates :body, presence: true
end

myblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = post.comments.new(comment_params)
        if comment.save
            flash[:success] = "コメントを1件作成しました"
        else
            flash[:error] = "コメントの作成に失敗しました"
        end
        redirect_to post_path(post)
    end

    def show
        comment
        render :edit
    end

    def edit
        comment
    end

    def update
        if comment.update(comment_params)
            redirect_to post_path(post)
            flash[:success] = "コメントを1件更新しました"
        else
            render :edit
            flash.now[:error] = "コメントの更新に失敗しました"
        end
    end

    def destroy
        if comment.destroy
            flash[:success] = "コメントを1件削除しました"
        else
            flash[:error] = "コメントの削除に失敗しました"
        end
        redirect_to post_path(post)
    end


    private
        def comment_params
            params.require(:comment).permit(:body)
        end

        def post
            @post ||= Post.find(params[:post_id])
        end
    
        def comment
            @comment ||= post.comments.find(params[:id])
        end
end

myblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all.order(created_at: 'desc')
    end

    def show
        post
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if post.save
            redirect_to posts_path
            flash[:success] = "#{post.title}を作成しました" 
        else
            render :new
            flash.now[:error] = "新規記事の作成に失敗しました"
        end
    end

    def edit
        post
    end
    
    def update
        if post.update(post_params)
            redirect_to posts_path
            flash[:success] = "#{post.title}を更新しました"
        else
            render :edit
            flash.now[:error] = "記事の更新に失敗しました"
        end
    end

    def destroy
        if post.destroy
            flash[:success] = "#{post.title}を削除しました"
        else
            flash[:error] = "記事の削除に失敗しました"
        end
        redirect_to posts_path
    end


    private
        def post_params
            params.require(:post).permit(:title, :body)
        end

        def post
            @post ||= Post.find(params[:id])
        end
end

myblog/app/helpers/application_helper.rb
module ApplicationHelper
    def page_title
        title = "自作ブログ"
        title = @page_title + " | " + title if @page_title
    end
end

myblog/app/views/comments/edit.html.slim
- @page_title = @post.title + "コメント編集"

h2 
    = @post.title
p
    = simple_format @post.body


h3 
    コメント編集中
    = form_with model: @comment, url: post_comment_path , local:true  do |f|
        p
            = f.text_field :body, placeholder: '内容を入力してください'
            - if @comment.errors.messages[:body].any?
            span.error
                = @comment.errors.messages[:body][0]
        p
            = f.submit

myblog/app/views/layouts/application.html.slim
doctype html
html
  head
    title 
      = page_title
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    .container
    h1
        = link_to image_tag('logo.png', class: 'logo'), root_path
    == yield

myblog/app/views/posts/_form.html.slim
= form_with model: @post, local: true do |f|
    p
        = f.text_field :title, placeholder: 'タイトルを入力してください'
        - if @post.errors.messages[:title].any?
        span.error
            = @post.errors.messages[:title][0]
    p
        = f.text_area :body, placeholder: '内容を入力してください'
        - if @post.errors.messages[:body].any?
        span.error
            = @post.errors.messages[:body][0]
    p
        = f.submit

myblog/app/views/posts/edit.html.slim
- @page_title = @post.title + "編集"

h2 記事編集
== render 'form'

myblog/app/views/posts/index.html.slim
- @page_title = "一覧" 

h2 
    記事一覧
    = link_to '新規作成', new_post_path, class: 'header-menu'
p
    =flash[:success]
    =flash[:error]
ul
    - @posts.each do |post|
        li 
            = link_to post.title, post_path(post)
            = link_to '[編集]', edit_post_path(post), class: 'command'
            = link_to '[削除]', post_path(post), method: :delete, class: 'command', data: {confirm: '本当によろしいですか?'}
        

myblog/app/views/posts/new.html.slim
- @page_title = "新規作成"

h2 新規記事作成
== render 'form'

myblog/app/views/posts/show.html.slim
- @page_title = @post.title

h2
    = @post.title
p
    =flash[:success]
    =flash[:error]
p
    = simple_format @post.body

h3 コメント
- if @post.comments.any?
    ul
    - @post.comments.each do |comment|
        li 
            = comment.body
            = link_to '[編集]', edit_post_comment_path(@post, comment), class: 'command'
            = link_to '[削除]', post_comment_path(@post, comment), method: :delete, class: 'command', data: {confirm: '本当によろしいですか?'}


= form_with model: (@comment = @post.comments.new), url: post_comments_path(@post),local: true  do |f|
    p
        = f.text_field :body, placeholder: 'コメントを入力できます'
        - if @comment.errors.messages[:body].any?
        span.error
            = @comment.errors.messages[:body][0]
    p
        = f.submit